In [1]:
import numpy as np

In [33]:
#arange函数,得到0-14共15个数据
print np.arange(15)

#reshape 变换为3x5矩阵
a = np.arange(15).reshape(3,5)

print '-------------------------------------------------------我是可爱的分割线'
print a


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------------------------------------------------我是可爱的分割线
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
#矩阵属性操作
a.shape

(3, 5)

In [5]:
#维度 2D = ndim = 2
a.ndim

2

In [7]:
#矩阵类型
a.dtype.name

'int64'

In [8]:
#矩阵size
a.size

15

In [9]:
#注意括号  创建3x4的零矩阵
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#创建3x4,  数据类型为int32型的'1'矩阵
np.ones((3,4),dtype = 'int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [12]:
#np.arange()函数,从10开始到<30结束,间隔为5
a = np.arange(10, 30, 5)

In [13]:
a

array([10, 15, 20, 25])

In [14]:
a = np.arange(12).reshape(3,4)

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
#random默认为-[-1,1]区间内  random2行3列的矩阵  随机初始化
a = np.random.random((2,3))

In [20]:
a

array([[0.11418455, 0.72444608, 0.16181086],
       [0.96669065, 0.3322093 , 0.70053602]])

In [23]:
from numpy import pi
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [34]:
from numpy import pi
a = np.linspace(0, 2*pi, 100)

In [35]:
a

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [37]:
#数学运算
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print a
print '--------------'

print b
print '--------------'

c = a - b 
print c

#乘方
d = b**2
print '--------------'
print d 

e = c-1 
print '--------------'
print e

print '--------------'
print a<35

[10 20 30 40]
--------------
[0 1 2 3]
--------------
[10 19 28 37]
--------------
[0 1 4 9]
--------------
[ 9 18 27 36]
--------------
[ True  True  True False]


In [30]:
#矩阵点乘和
A = np.array([[1,2],
              [0,2]])

B = np.array([[2,1],
              [3,4]])
print A
print '--------------'
print B
print '--------------'

#矩阵对应位置相乘
print A*B
print '--------------'

#矩阵乘法
print A.dot(B)

#np.dot(A,B)和A.dot(B)都是正确的用法,可以得到相同的结果
print np.dot(A,B)
print '--------------'



[[1 2]
 [0 2]]
--------------
[[2 1]
 [3 4]]
--------------
[[2 2]
 [0 8]]
--------------
[[8 9]
 [6 8]]
--------------
[[8 9]
 [6 8]]


In [31]:
print help(np.dot)

Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Se