In [2]:
import numpy as np

In [42]:
#复制操作
#1  直接赋值 a,b完全一样  只是称呼不同
a = np.arange(12)

b = a
print b is a
print '-------------------------------------------------------我是可爱的分割线'

#对b的shape做操作  a的shape也会变
b.shape = (3,4)
print a.shape
print '-------------------------------------------------------我是可爱的分割线'

#a,b具有相同的ID,存储位置一样
print id(a)
print '-------------------------------------------------------我是可爱的分割线'

print id(b)

True
-------------------------------------------------------我是可爱的分割线
(3, 4)
-------------------------------------------------------我是可爱的分割线
139921802922224
-------------------------------------------------------我是可爱的分割线
139921802922224


In [43]:
#2 view()操作  c是一个新的data,不过含有和a一样的数据
c = a.view()
print c is a
print '-------------------------------------------------------我是可爱的分割线'

#c的shape改变  a不会改变shape
c.shape = 2,6
print a.shape
print '-------------------------------------------------------我是可爱的分割线'

#改变c 里面的data ,a也会发生改变,二者公用一套data
c[0,3] = 55
print a
print '-------------------------------------------------------我是可爱的分割线'

print id(c)
print '-------------------------------------------------------我是可爱的分割线'

print id(a)

False
-------------------------------------------------------我是可爱的分割线
(3, 4)
-------------------------------------------------------我是可爱的分割线
[[ 0  1  2 55]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------我是可爱的分割线
139921802921584
-------------------------------------------------------我是可爱的分割线
139921802922224


In [45]:
#3  copy()
#d是a经过copy操作之后的新数据   对d进行操作不会影响a
d = a.copy()

print d is a
print '-------------------------------------------------------我是可爱的分割线'


d[0,0] = 99



print d
print '-------------------------------------------------------我是可爱的分割线'

print a

False
-------------------------------------------------------我是可爱的分割线
[[99  1  2 55]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------------------我是可爱的分割线
[[ 0  1  2 55]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
#利用sin函数构造数据
data = np.sin(np.arange(20)).reshape((5,4))
print data

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [38]:
#按照列找到最大值的索引 axis = 0对所有列执行操作
index = np.argmax(data, axis = 0)
print index

[2 0 3 1]


In [39]:
#利用索引打印出最大值   index    [[2,0,3,1]
 #                   range(4) [0,1,2,3]]  对应作为索引,得到data中的最大值
print data.shape[1]
print '-------------------------------------------------------我是可爱的分割线'

print data[index, range(data.shape[1])]

4
-------------------------------------------------------我是可爱的分割线
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [17]:
#扩展操作
a = np.arange(0, 40, 10)
print a 

[ 0 10 20 30]


In [19]:
print np.tile(a, (2,2))

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [26]:
#排序操作  默认从小到大排序
a = np.array([[1,4,2],
             [3,6,2]])

#axis = 1 按照行进行排序
a.sort(axis = 1)
# np.sort(a, axis = 1)
print a

[[1 2 4]
 [2 3 6]]


In [28]:
#axis = 0按照列进行排序
np.sort(a, axis = 0)

array([[1, 2, 4],
       [2, 3, 6]])

In [41]:
a = np.array([1,4,2])

#argsort得到顺序点索引
index = np.argsort(a)
print index
print '-------------------------------------------------------我是可爱的分割线'

#根据上一步索引可以得到排序后的结果
print a[index]

[0 2 1]
-------------------------------------------------------我是可爱的分割线
[1 2 4]
