In [34]:
import numpy as np

#help操作
print help(np.genfromtxt)
txt = np.genfromtxt('read.txt', delimiter=',',dtype=str)
#1999,tom,tree
#1998,jerry,peach

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
    

IOError: read.txt not found.

In [40]:
#创建矩阵
matrix = np.array([[1,2,3], 
                   [1,2,3],
                   [1,2,3]])


print matrix
print '------------------我是可爱的分割线'
#打印出matrix的shape
print matrix.shape


[[1 2 3]
 [1 2 3]
 [1 2 3]]
------------------我是可爱的分割线
(3, 3)


In [44]:
#-*- coding:utf-8 -*_
#创建数组
numbers = np.array([1, 2, 3, 4])

print numbers
print '-----------------------我是可爱的分割线'
#默认类型为int64
numbers.dtype

[1 2 3 4]
-----------------------我是可爱的分割线


dtype('int64')

In [43]:
#numpy array 强调里面都为同一类型,  改变4为4.0,  数组数值类型都会由整型变为浮点型
numbers = np.array([1, 2, 3, 4.0])

print numbers
print '----------------------我是可爱的分割线'
numbers.dtype

[1. 2. 3. 4.]
----------------------我是可爱的分割线


dtype('float64')

In [7]:
#1D 数组切片操作
vector = np.array([1, 2, 3, 4])

#list或者matrix数据下标都从0开始

#:2代表0,1即vector的前两个数据

print vector[:2]

[1 2]


In [52]:
#2D 矩阵切片操作
matrix = np.array([[1,1,2], 
                   [2,3,4], 
                   [3,3,4]])

#[:,1]代表matrix的所有行的第二列
print matrix[:,1]
print '----------------------我是可爱的分割线'
print matrix[:,1:2]

[1 3 3]
----------------------我是可爱的分割线
[[1]
 [3]
 [3]]


In [10]:
#判断操作
vector = np.array([10, 20, 20, 30])

#对vector里面所有数据进行是否等于10的判断,输出结果类型为bool型
vector == 10

array([ True, False, False, False])

In [50]:
matrix = np.array([[1,5,3],
                   [2,4,4],
                   [3,4,5]])

matrix == 4

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [48]:
#先执行判断操作
#以bool类型值作为索引

number = (matrix == 4)

print number
print '----------------------我是可爱的分割线'
print matrix[number]

[[False False False]
 [False  True  True]
 [False  True False]]
----------------------我是可爱的分割线
[4 4 4]


In [51]:
index = (matrix[:,0] == 1)

print index
print '----------------------我是可爱的分割线'
print matrix[index, :]

[ True False False]
----------------------我是可爱的分割线
[[1 5 3]]
