In [28]:
import numpy as np

In [2]:
print help(np.sqrt)

Help on ufunc object:

sqrt = class ufunc(__builtin__.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arr

In [33]:
import numpy as np

a = np.arange(3)
print a 
print '-------------------------------------------------------我是可爱的分割线'

#e^a
print np.exp(a)
print '-------------------------------------------------------我是可爱的分割线'

#开根号
print np.sqrt(a)

[0 1 2]
-------------------------------------------------------我是可爱的分割线
[1.         2.71828183 7.3890561 ]
-------------------------------------------------------我是可爱的分割线
[0.         1.         1.41421356]


In [35]:
#floor代表向下取整 ,随机选取[-10,10]区间内数据,初始化为3x4矩阵
a = np.floor(10*np.random.random((3,4)))
print a 
print '-------------------------------------------------------我是可爱的分割线'

#ravel函数使矩阵拉平为一个向量
print np.ravel(a)
print a.ravel()
print '-------------------------------------------------------我是可爱的分割线'

#向量重新reshape为一个矩阵
print a.reshape((6,2))
print '-------------------------------------------------------我是可爱的分割线'

#-1代表自动计算得到的值  即12/3 = 4
print a.reshape(3,-1)
print '-------------------------------------------------------我是可爱的分割线'

#矩阵转置
print a.T

[[4. 8. 9. 2.]
 [9. 8. 5. 5.]
 [0. 4. 7. 7.]]
-------------------------------------------------------我是可爱的分割线
[4. 8. 9. 2. 9. 8. 5. 5. 0. 4. 7. 7.]
[4. 8. 9. 2. 9. 8. 5. 5. 0. 4. 7. 7.]
-------------------------------------------------------我是可爱的分割线
[[4. 8.]
 [9. 2.]
 [9. 8.]
 [5. 5.]
 [0. 4.]
 [7. 7.]]
-------------------------------------------------------我是可爱的分割线
[[4. 8. 9. 2.]
 [9. 8. 5. 5.]
 [0. 4. 7. 7.]]
-------------------------------------------------------我是可爱的分割线
[[4. 9. 0.]
 [8. 8. 4.]
 [9. 5. 7.]
 [2. 5. 7.]]


In [36]:
#stack 堆叠操作
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print a 
print '-------------------------------------------------------我是可爱的分割线'

print b
print '-------------------------------------------------------我是可爱的分割线'

#hstack()代表横向堆叠a,b
print np.hstack((a,b))
print '-------------------------------------------------------我是可爱的分割线'

#vstack()代表竖向堆叠a,b
print np.vstack((a,b))

[[1. 6.]
 [7. 2.]]
-------------------------------------------------------我是可爱的分割线
[[0. 0.]
 [9. 1.]]
-------------------------------------------------------我是可爱的分割线
[[1. 6. 0. 0.]
 [7. 2. 9. 1.]]
-------------------------------------------------------我是可爱的分割线
[[1. 6.]
 [7. 2.]
 [0. 0.]
 [9. 1.]]


In [39]:
#split切分操作
a  = np.floor(10*np.random.random((2,12)))
print a
print '---------------------------------------------------------------我是可爱的分割线'

#对a按照行进行切分为3段, 12列平均分配,每4个为一段即[0,1,2,3],[4,5,6,7],[8,9,10,11]
print np.hsplit(a,3)
print '---------------------------------------------------------------我是可爱的分割线'

#对a 设定切分点,hsplit对a按照列进行切分 [0,1]分为1段 [2,3]分为一段 剩余为一段
print np.hsplit(a,(2,4))
print '----------------------------------------------------------------我是可爱的分割线'

a  = np.floor(10*np.random.random((12,2)))
#vsplit对a按照行进行切分 12行平均分配,每4个为一段即[0,1,2,3],[4,5,6,7],[8,9,10,11]
print np.vsplit(a, 3)

[[3. 0. 9. 0. 4. 9. 1. 5. 6. 1. 0. 7.]
 [1. 1. 7. 9. 1. 3. 1. 5. 9. 1. 1. 5.]]
---------------------------------------------------------------我是可爱的分割线
[array([[3., 0., 9., 0.],
       [1., 1., 7., 9.]]), array([[4., 9., 1., 5.],
       [1., 3., 1., 5.]]), array([[6., 1., 0., 7.],
       [9., 1., 1., 5.]])]
---------------------------------------------------------------我是可爱的分割线
[array([[3., 0.],
       [1., 1.]]), array([[9., 0.],
       [7., 9.]]), array([[4., 9., 1., 5., 6., 1., 0., 7.],
       [1., 3., 1., 5., 9., 1., 1., 5.]])]
----------------------------------------------------------------我是可爱的分割线
[array([[1., 2.],
       [3., 1.],
       [5., 9.],
       [0., 9.]]), array([[4., 8.],
       [2., 2.],
       [5., 2.],
       [5., 9.]]), array([[9., 3.],
       [1., 5.],
       [3., 2.],
       [0., 2.]])]
